= Permitting Considerations

This document details the ideal permit application, construction, and maintenance processes for Municipal Fiber (Reference Google Fiber). We’ve found that this approach to permitting and construction works well for a network build of this size. As part of the checklist, we ask that your city review each of these items. In cases where your city has different processes and requirements from those outlined, please provide detailed notes on what the city’s existing requirements or process are, so our engineering teams can work collaboratively to create a process that will work at scale.

== Permitting Process

Recommended Fiber’s Process and Standards:

* Plan to submit all permit application material to you electronically.
* For underground construction, Plan on submitting plan view only.
* All responses, including approvals, should be sent back electronically.
* Permit applications will include the applicable area and the duration of at least one hundred and eighty (180) days to complete the proposed installation.
* The applicable area to be as large as possible, ideally covering the entire city. If not, the applicable area should be a minimum of either:

Minimum Ten to twenty-thousand (20,000) households three-hundred (300) route miles of underground installation.
We are looking for a response within ten (10) days of submitting the permit application.
If a permit application is not approved, we need to receive a detailed list of alterations needed to get the permit approved.

The city should provide Permit Application communication through a single point of contact.

== Construction Process

Recommended Fiber’s Process and Standards (Subject to change per Fiber Provider construction process)
The preferred installation method may be shown on the plan view of the permit, but will be determined by field conditions at the time of construction.
Fiber will implement the city’s standard traffic control plan at the time of installation of the XXX Fiber network.
The underground construction methods may include but are not limited to micro trench, plow, open trench, directional bore and pneumatic bore.
Twenty-four inch (24”) horizontal separation from existing facilities will be maintained during installation, except where existing obstructions, underground congestion, or other reasons necessitate a lesser separation.
Twelve inch (12”) vertical separation from existing facilities will be maintained during installation, except where existing obstructions, underground congestion, or other reasons necessitate a lesser separation.
Twenty-four (24”) depth below existing grade will be maintained during installation, except where existing obstructions, underground congestion, or other reasons necessitate a shallower depth.
When an open trench is utilized for construction in concrete or asphalt, a T-Cut method will be utilized for restoration, except where this method is not practicable.
A single, full sidewalk panel will be replaced when any portion of a sidewalk panel is impacted, except by potholing.
Pothole restoration will be limited to the circular area directly impacted by potholing activity, including in sidewalk areas.
Plan to maintain an as-built description of changes required during the course of installation due to conditions on the ground. For proprietary reasons, Google
Fiber will provide a PDF version of the plan view as-builts of the underground installation when required.

=== Line Work

* Standard traffic control plan.
* Utility System Engineering Design Manual
* Utility System Construction Standards
* Line-clearing and Tree-Trimming Service
* Arborist requirements for working around trees

=== Building Code

* Fire Safety
* Electrical/Telecommunications Wiring
* Grounding
* Utilities
* Maintenance

== Recommended Fiber’s Process and Standards:

For Fiber maintenance work activities, XXX Fiber will provide fortyeight (48) hours’ electronic notice to the Right-of-Way Operator’s maintenance department before commencing planned work.
Service wire to the home (drops) installation will be considered a maintenance activity.
