= Zone Services

== Service Definitions

This guide provides a comprehensive set of requirements and guidelines for compliance in building and operating the active components of a broadband utility and is meant as a companion to the commercialization agreement in Digital Ubiquity Capital projects. In order to achieve repeatable outcome and blueprints it is important that all projects under Digital Ubiquity Capital governance follow the evolution of this guide when they are involving broadband utilities.

=== Bitstream Services


=== Enterprise PE


=== Lawful Intercept


== Service Level Requirements

Digital infrastructures are the foundational layer that are required to power tomorrow’s economy in the same way that railroads, roads, power and even waters ways have contributed to societies’ economic developments. Recent world events have accelerated radical digital transformations affecting the way we interact, work and live. It has demonstrated that in this upside down world,  health, education and government all need to leverage the digital infrastructures in a new way. This is why investing in partnership with communities is what will 

