= Welcome to Digital Ubiquity Capital
:toc:

== About this guide

This guide provides a comprehensive set of requirements and guidelines for compliance in building and operating the active components of a broadband utility and is meant as a companion to the commercialization agreement in Digital Ubiquity Capital projects. In order to achieve repeatable outcome and blueprints it is important that all projects under Digital Ubiquity Capital governance follow the evolution of this guide when they are involving broadband utilities.

== About Digital Ubiquity Capital

Digital infrastructures are the foundational layer that are required to power tomorrow’s economy in the same way that railroads, roads, power and even waters ways have contributed to societies’ economic developments. Recent world events have accelerated radical digital transformations affecting the way we interact, work and live. It has demonstrated that in this upside down world,  health, education and government all need to leverage the digital infrastructures in a new way. This is why investing in partnership with communities is what will make these infrastructures sustainable and will empower tomorrow’s economic needs. At Digital Ubiquity Capital we focus on removing the complexities in these investments, making them accessible as Environmental, Social and Corporate Governance (ESG) investment instruments to institutional investments funds, family offices, and even individuals from the communities themselves.

All projects that are financed by Digital Ubiquity Capital must comply with the frame of reference and values that makes them qualify for ESG investments and become economic development tools for the communities. Moreover, they must be done in partnership with various stakeholders in the communities, providing shared value and sustainable financial returns.







