= Overview

== Description

Community Zones are named as such as they are connecting communities by providing the middle-mile infrastructure and services to access zones, entreprises and tower sites. These zones are meant to offer carrier-grade networks within a community mainly by providing services from the market zones into the communities. As such the community zone has the requirements of middle-mile networking with the appropriate level of traffic engineering, path protection and isolation required for a multi-tenant carrier grade infrastructure.

== Problem

The operators today each have their own OSS/BSS methodology and processes which at scale can lead to internal standardization. Moreover, everytime there is a partnership with other operators, one must agree on terms, variations, expectations, processes and interfaces even in leveraging the same underlying services and capacities. Moreover, SLA break, billing errors and disputes between operators is frequent can becoming challenging situations. Broadband Utility while of significant size usally will pale in comparison to incumbent telecom providers or large aggregate carriers. For the tenants of the broadband utilities or operator partners it is important that all the utilities have a standardized interface for interaction in order to federate coverage across utility projects and their partners. This part of the specification focuses on providing that standardized automated experience by leveraging industry standards for interoperability and automation between leading edge carriers.

== Market Definition

The market for the access zone is made up of :

* Retail Customers (Residental, SOHO, SME)
* Enterprise Customers (Direct Fiber Access)
* Wireless/Mobility Tower Sites (Fiber to the Tower)
* IoT / Industry 4.0 (Fiber to the Farm, etc.)

A limited set of services are defined to be able to address the requiements and compliance for meeting these customers under a multi-tenant infrastructure that provides the appropriate level of hardware isolation and capacities.

== Objectives

All projects that are financed by Digital Ubiquity Capital must comply with the frame of reference and values that makes them qualify for ESG investments and become economic development tools for the communities. Moreover, they must be done in partnership with various stakeholders in the communities, providing shared value and sustainable financial returns.







