= Overview

== Description

Community Zones are named as such as they are connecting communities by providing the middle-mile infrastructure and services to access zones, entreprises and tower sites. These zones are meant to offer carrier-grade networks within a community mainly by providing services from the market zones into the communities. As such the community zone has the requirements of middle-mile networking with the appropriate level of traffic engineering, path protection and isolation required for a multi-tenant carrier grade infrastructure.

== Problem

The operators today each have their own OSS/BSS methodology and processes which at scale can lead to internal standardization. Moreover, everytime there is a partnership with other operators, one must agree on terms, variations, expectations, processes and interfaces even in leveraging the same underlying services and capacities. Moreover, SLA break, billing errors and disputes between operators is frequent can becoming challenging situations. Broadband Utility while of significant size usally will pale in comparison to incumbent telecom providers or large aggregate carriers. For the tenants of the broadband utilities or operator partners it is important that all the utilities have a standardized interface for interaction in order to federate coverage across utility projects and their partners. This part of the specification focuses on providing that standardized automated experience by leveraging industry standards for interoperability and automation between leading edge carriers.

== Market Definition

The market for the community zone is made up of :

* Carrier Customers 
* Enterprise Customers
* Retail Service Providers

The community zone also must link all the access zones together by providing them with a protected, diverse and reliable set of links and also cather to enterprise or important physical network access point (PNAP) services that would require the services.. It also must be able to provide proper point-of-handover in disaggregated network services to retail service providers. 

== Objectives

The community zone has been created to offer an automated and autonomous approach enabling end-to-end orchestration and automation across multiple providers networks in order to offer frictionless services to the enterprise and offer Software-defined Digital Services that lay the foundation of connected communities.







